# name: Deno

# on:
#   push:
#     branches: [production]

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: "3.87.119.101"
#         username: "ubuntu"
#         key: ${{ secrets.EC2KEY }}
#         port: 22
#         script: |
#           cd lienzo_urbano-backend
#           git pull
#           pm2 restart lienzo_urbano-backend