name: Deno

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "3.85.226.134"
        username: "ubuntu"
        key: ${{ secrets.EC2KEY }}
        port: 22
        script: |
          cd lienzo_urbano-backend