name: Deno

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "54.85.209.94"
        username: "ubuntu"
        key: ${{ secrets.EC2KEY }}
        port: 22
        script: |
          cd lienzo_urbano-backend
          sudo git pull https://BETLOPAGU@github.com/BETLOPAGU/lienzo_urbano-backend
          yarn install --production
          yarn prisma:sync
          yarn build
          pm2 update